- name: download mysql from repository
  get_url: url={{ mysqlserver_path }} dest=/opt

- name: download mysql from repository
  get_url: url={{ mysqldevel_path }} dest=/opt

- name: download mysql from repository
  get_url: url={{ mysqlclient_path }} dest=/opt

- name: yum install mysql
  yum: name={{ item }} state=present
  with_items:
    - libaio
    - perl-Module-Install.noarch
    - /opt/MySQL-server-5.6.28-1.linux_glibc2.5.x86_64.rpm
    - /opt/MySQL-devel-5.6.28-1.linux_glibc2.5.x86_64.rpm
    - /opt/MySQL-client-5.6.28-1.linux_glibc2.5.x86_64.rpm

- name: create new mysql secuert password
  command: chdir=/usr/bin/mysql_install_db

- name: delete config
  command: sudo rm -rf /etc/my.cnf

- name: copy config
  copy: src=/usr/share/mysql/my-default.cnf dest=/etc/my.cnf

- name: copy the mysql script
  copy: src=mysql.sh dest=/opt mode=0755

- name: run mysql shell
  script: /opt/mysql.sh

- name: enable mysql to be started at boot
  service: name=mysql enabled=yes state=started

